project(Chapter_09 CXX)
add_subdirectory(exercise_9.12_rectangle)
add_subdirectory(exercise_9.12and13)
add_subdirectory(exercise_9.14)
add_subdirectory(exercise_9.4_time_class)
add_subdirectory(exercise_9.5_date_class)
add_subdirectory(exercise_9.6_complex_class)
add_subdirectory(exercise_9.7and10_time)
add_subdirectory(exercise_9.8_main)
