cmake_minimum_required(VERSION 3.10)
project(CppFundamentalsDeitel CXX)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

if(MSVC)
    add_compile_options(/W4)
else()
    add_compile_options(-Wall -Wextra -pedantic)
endif()

add_subdirectory(Chapter_07)
add_subdirectory(Chapter_09)
add_subdirectory(Chapter_10)
add_subdirectory(Chapter_11)
add_subdirectory(Chapter_13)
add_subdirectory(Chapter_14)
add_subdirectory(Chapter_15)
add_subdirectory(Chapter_16)
add_subdirectory(Chapter_17)
add_subdirectory(Chapter_20)
add_subdirectory(Chapter_21)
